{
    "route": "{{{route}}}",
    "name": "{{{name}}}",
    "page_name": "{{{page_name}}}",
    "model": "{{{model}}}",
    "controller": "{{{controller_name}}}",
    "api_controller": "{{{controller_api_name}}}",
    "activity_log":false,
    "override_add": "",
    "override_edit": "",
    "override_view": "",
    "override_list": "",
    "api": true,
    "frontend": false,
    "paginate": true,
    "paginate_join": "",
    "portal":  "{{{portal}}}",
    "is_crud": true,
    "method_edit_pre": "",
    "is_add": true,
    "is_edit": true,
    "is_delete": false,
    "is_real_delete": false,
    "is_list": true,
    "is_view": true,
    "import": false,
    "export": false,
    "is_filter": true,
    "all_records": true,
    "active_only": false,
    "method": "",
    "method_add": "",
    "method_edit": "",
    "method_list": "",
    "method_view": "",
    "method_add_success": "",
    "method_edit_success": "",
    "method_list_success": "",
    "method_view_success": "",
    "method_delete_success": "",
    "custom_view_add": "",
    "custom_view_edit": "",
    "custom_view_list": "",
    "custom_view_view": "",
    {{{listing_fields}}}
    {{{listing_headers}}}
    {{{listing_rows}}}
    "listing_actions": [],
    {{{filter_fields}}}
    {{{add_fields}}}
    {{{edit_fields}}}
    {{{view_fields}}}
    "autocomplete": "",
    "dynamic_mapping_add": {},
    "dynamic_mapping_edit": {},
    "dynamic_mapping_view": {},
    "dynamic_mapping": {},
    "load_libraries": []
}