cd ../release;
rm -rf *;
cd ../;
chown -R www-data:www-data mkdcore;
chmod -R 775 mkdcore;
cp -R mkdcore/initialize/* release;
cp -R vendor release;
cp -R composer.json release;
cp -R composer.lock release;
cd release;
chown -R www-data:www-data *;
chmod -R 775 *;